name: Atualiza Agenda Sympla

on:
  schedule:
    - cron: '0 8 * * *' 
  workflow_dispatch: 

jobs:
  atualizar:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar Dependências do Robô
      run: |
        npm init -y
        npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth

    - name: Rodar a raspagem de dados
      run: node scraper.js

    - name: Commit e Push do agenda.json
      run: |
        git config --global user.name "Robo Kynto"
        git config --global user.email "robo@kynto.com.br"
        git add agenda.json
        git commit -m "🤖 Agenda de shows atualizada via Web Scraping" || exit 0
        git push
